[2020-06-05 03:26:06,468] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: tutorial.sleep 2015-06-01T00:00:00+00:00 [queued]>
[2020-06-05 03:26:06,485] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: tutorial.sleep 2015-06-01T00:00:00+00:00 [queued]>
[2020-06-05 03:26:06,485] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 03:26:06,485] {taskinstance.py:880} INFO - Starting attempt 1 of 4
[2020-06-05 03:26:06,485] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 03:26:06,495] {taskinstance.py:900} INFO - Executing <Task(BashOperator): sleep> on 2015-06-01T00:00:00+00:00
[2020-06-05 03:26:06,497] {standard_task_runner.py:53} INFO - Started process 14045 to run task
[2020-06-05 03:26:06,591] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: tutorial.sleep 2015-06-01T00:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-06-05 03:26:06,614] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/jk/bwh6mk3d71s4w_mb373dxcsr0000gn/T
[2020-06-05 03:26:06,616] {bash_operator.py:103} INFO - Temporary script location: /var/folders/jk/bwh6mk3d71s4w_mb373dxcsr0000gn/T/airflowtmp0ww8qx7y/sleepbrvlqdcs
[2020-06-05 03:26:06,617] {bash_operator.py:115} INFO - Running command: sleep 5
[2020-06-05 03:26:06,629] {bash_operator.py:122} INFO - Output:
[2020-06-05 03:26:09,675] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 14045
[2020-06-05 03:26:09,676] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2020-06-05 03:26:09,676] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2020-06-05 03:26:09,678] {helpers.py:291} INFO - Process psutil.Process(pid=14047, status='terminated') (14047) terminated with exit code None
[2020-06-05 03:26:09,687] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2020-06-05 03:26:09,692] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-05 03:26:09,739] {helpers.py:291} INFO - Process psutil.Process(pid=14045, status='terminated') (14045) terminated with exit code 1
[2020-06-05 03:26:09,740] {helpers.py:291} INFO - Process psutil.Process(pid=14046, status='terminated') (14046) terminated with exit code None
